<a href="https://colab.research.google.com/github/matalhim/mephi/blob/master/Poisson_distribution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##распределение Пуассона
$P_{n} = \frac{\lambda^n}{n!} \cdot e^{-\lambda}$
<br>
<br>
Доверительный интервал 0.95

Условие на правую границу погрешности

$\sum_{n=0}^{n=k} P_{n, \lambda_{r}} = 0.025$

Условие на левую границу погрешности

$\sum_{n=k}^{\infty} P_{n, \lambda_{l}} = 0.025$, либо $\sum_{n=0}^{k-1} P_{n, \lambda_{l}}=0.975$
<br>
<br>
$\sum_{n=0}^{k} P_{n, \lambda} = \sum_{n=0}^{k}\frac{\lambda^n}{n!} \cdot e^{-\lambda} = e^{-\lambda}(1 +
\frac{\lambda}{1!} + \frac{\lambda^2}{2!} + \frac{\lambda^3}{3!}+...+
\frac{\lambda^k}{k!})
$
<br>
<br>
Правая граница:

$e^{-\lambda_{r}}(1 +
\frac{\lambda_{r}}{1!} + \frac{\lambda_{r}^2}{2!} + \frac{\lambda_{r}^3}{3!}+...+
\frac{\lambda_{r}^k}{k!}) = 0.025\\
k = 0,1,...,30$
<br>
<br>
Левая граница:

$e^{-\lambda_{l}}(1 +
\frac{\lambda_{l}}{1!} + \frac{\lambda_{l}^2}{2!} + \frac{\lambda_{l}^3}{3!}+...+
\frac{\lambda_{l}^{k-1}}{(k-1)!}) = 0.975\\
k = 1,...,30$
<br>
<br>

$
\sigma_{l} = k - \lambda_{l}\\
\sigma_{r} = \lambda_{r} - k
$



In [ ]:
from scipy.optimize import bisect, newton, root_scalar
import numpy as np
import matplotlib.pyplot as plt
import numpy as np
import math

def calculate_lambda_right(k):
    def f(x):
            return np.exp(-x) * np.sum([x ** n / math.factorial(n) for n in range(k+1)]) - 0.025
    a, b = 0, 1
    while np.sign(f(a)) == np.sign(f(b)):
        b += 1

    return bisect(f, a, b), root_scalar(f, method='newton', x0=1).root, root_scalar(f, method='brentq', bracket=[a, b]).root, root_scalar(f, method='ridder', bracket=[a, b]).root


def calculate_lambda_left(k):
    def f(x):
        return np.exp(-x) * np.sum([x ** n / math.factorial(n) for n in range(k)]) - 0.975

    a, b = 0, 1
    while np.sign(f(a)) == np.sign(f(b)):
        b += 1

    return bisect(f, a, b), root_scalar(f, method='newton', x0=1).root, root_scalar(f, method='brentq', bracket=[a, b]).root, root_scalar(f, method='ridder', bracket=[a, b]).root



def calculate_sigma_right(k, lamda):
    return lamda - k

def calculate_sigma_left(k, lamda):
    return k - lamda

print("\nПравые погрешности")
header = "{:<20}{:<20}{:<20}{:<20}{:<20}{:<20}{:<20}{:<20}{:<20}".format(
    "k", "Bisect lamda", 'sigma', "Newton lamda", 'sigma', "Brentq lamda", 'sigma', "Ridder lamda", 'sigma'
)
header = header.replace('sigma', 'σᵣ'.ljust(1)).replace('lamda', 'λᵣ'.ljust(8))
table = ""
for k in range(31):
    right_bisect, right_newton, right_brentq, right_ridder = calculate_lambda_right(k)

    right_sigma_bisect = calculate_sigma_right(k, right_bisect)
    right_sigma_newton = calculate_sigma_right(k, right_newton)
    right_sigma_brentq = calculate_sigma_right(k, right_brentq)
    right_sigma_ridder = calculate_sigma_right(k, right_ridder)

    row = "{:<20}{:<20.6f}{:<20.6f}{:<20.6f}{:<20.6f}{:<20.6f}{:<20.6f}{:<20.6f}{:<20.6f}\n".format(
        k, right_bisect, right_sigma_bisect, right_newton, right_sigma_newton, right_brentq, right_sigma_brentq, right_ridder, right_sigma_ridder
    )
    table += row

print(header + "\n" + table)

print("\nЛевые погрешности:")
header = "{:<20}{:<20}{:<20}{:<20}{:<20}{:<20}{:<20}{:<20}{:<20}".format(
    "k", "Bisect lamda", 'sigma', "Newton lamda", 'sigma', "Brentq lamda", 'sigma', "Ridder lamda", 'sigma'
)
header = header.replace('sigma', 'σₗ'.ljust(1)).replace('lamda', 'λₗ'.ljust(10))
table = ""
for k in range(31):
    if k != 0:
        left_bisect, left_newton, left_brentq, left_ridder = calculate_lambda_left(k)

        left_sigma_bisect = calculate_sigma_left(k, left_bisect)
        left_sigma_newton = calculate_sigma_left(k, left_newton)
        left_sigma_brentq = calculate_sigma_left(k, left_brentq)
        left_sigma_ridder = calculate_sigma_left(k, left_ridder)

        row = "{:<20}{:<20.6f}{:<20.6f}{:<20.6f}{:<20.6f}{:<20.6f}{:<20.6f}{:<20.6f}{:<20.6f}\n".format(
            k, left_bisect, left_sigma_bisect, left_newton, left_sigma_newton, left_brentq, left_sigma_brentq,  left_ridder, left_sigma_ridder)
    else:
        row = "{:<20}{:<20}{:<20}{:<20}{:<20}{:<20}{:<20}{:<20}{:<20}\n".format(
            k, 0, 0, 0, 0, 0, 0, 0, 0)

    table += row

print(header + "\n" + table)



Правые погрешности


<ipython-input-161-1e7d8b159809>:9: RuntimeWarning: overflow encountered in exp
  return np.exp(-x) * np.sum([x ** n / math.factorial(n) for n in range(k+1)]) - 0.025


k                   Bisect λᵣ              σᵣ               Newton λᵣ              σᵣ               Brentq λᵣ              σᵣ               Ridder λᵣ              σᵣ               
0                   3.688879            3.688879            3.688879            3.688879            3.688879            3.688879            3.688879            3.688879            
1                   5.571643            4.571643            5.571643            4.571643            5.571643            4.571643            5.571643            4.571643            
2                   7.224688            5.224688            7.224688            5.224688            7.224688            5.224688            7.224688            5.224688            
3                   8.767273            5.767273            -462.094859         -465.094859         8.767273            5.767273            8.767273            5.767273            
4                   10.241589           6.241589            64.369060           60.369060      

<ipython-input-161-1e7d8b159809>:19: RuntimeWarning: overflow encountered in exp
  return np.exp(-x) * np.sum([x ** n / math.factorial(n) for n in range(k)]) - 0.975


k                   Bisect λₗ                σₗ               Newton λₗ                σₗ               Brentq λₗ                σₗ               Ridder λₗ                σₗ               
0                   0                   0                   0                   0                   0                   0                   0                   0                   
1                   0.025318            0.974682            0.025318            0.974682            0.025318            0.974682            0.025318            0.974682            
2                   0.242209            1.757791            0.242209            1.757791            0.242209            1.757791            0.242209            1.757791            
3                   0.618672            2.381328            0.618672            2.381328            0.618672            2.381328            0.618672            2.381328            
4                   1.089865            2.910135            1.089865            2.91013

Метод простой итерации

$x=\varphi(x)\\
x_{n+1} = \varphi(x_{n}); n = 0,1,2, ...$

сходимость:

$|\varphi(x_{*})| < 1$

In [ ]:
import numpy as np
from scipy.misc import derivative


def right_f(x, k):
    return np.exp(-x) * np.sum([x ** n / math.factorial(n) for n in range(k+1)]) - 0.025

def left_f(x, k):
    return np.exp(-x) * np.sum([x ** n / math.factorial(n) for n in range(k)]) - 0.975

def right_phi(x, k):
    return -np.log(0.025 / np.sum([x ** n / math.factorial(n) for n in range(k+1)]))

def left_phi(x, k):
    return -np.log(0.975 / np.sum([x ** n / math.factorial(n) for n in range(k)]))

def iteration_method(phi):
    epsilon = 1e-6
    k = 5
    x_current = 4
    x_next = 0
    x_values= []
    x_previous = 0
    for i in range(1000):
        x_next = phi(x_current, k)
        x_values.append(x_next)
        if np.abs((x_next - x_current) / (1 - (x_next - x_current) / (x_current - x_previous))) <= epsilon:
            break
        x_previous = x_current
        x_current = x_next
    print('итераций: ', i)
    return x_values



x_iterations_r = iteration_method(right_phi)
x_iterations_l = iteration_method(left_phi)
print('k = ', k)
print('λᵣ = {}\nλₗ = {}'.format(x_iterations_r[-1], x_iterations_l[-1]))

x_values_r = np.arange(np.min(x_iterations_r), np.max(x_iterations_r), 0.01)
x_values_l = np.arange(np.min(x_iterations_l), np.max(x_iterations_l), 0.01)
derivative_values_r = []
derivative_values_l = []
for x0 in x_values_r:
    derivative_values_r.append(derivative(right_phi, x0, args=(k,), dx=1e-6))
for x0 in x_values_l:
    derivative_values_l.append(derivative(left_phi, x0, args=(k,), dx=1e-6))

print('мсксимальный правый |φ(x∗)|: ', max(derivative_values_r, key=abs))
print('мсксимальный левый |φ(x∗)|: ', max(derivative_values_l, key=abs))

итераций:  18
итераций:  225
k =  5
λᵣ = 11.668331901544647
λₗ = 1.6234872782585719
мсксимальный правый |φ(x∗)|:  0.5498718964602745
мсксимальный левый |φ(x∗)|:  0.9414525266038254


<ipython-input-222-51c0304d37f4>:46: DeprecationWarning: scipy.misc.derivative is deprecated in SciPy v1.10.0; and will be completely removed in SciPy v1.12.0. You may consider using findiff: https://github.com/maroba/findiff or numdifftools: https://github.com/pbrod/numdifftools
  derivative_values_r.append(derivative(right_phi, x0, args=(k,), dx=1e-6))
<ipython-input-222-51c0304d37f4>:48: DeprecationWarning: scipy.misc.derivative is deprecated in SciPy v1.10.0; and will be completely removed in SciPy v1.12.0. You may consider using findiff: https://github.com/maroba/findiff or numdifftools: https://github.com/pbrod/numdifftools
  derivative_values_l.append(derivative(left_phi, x0, args=(k,), dx=1e-6))


Метод дихотомии

$f(a)\cdot f(b) < 0\\
|x_{n}-x_{n-1}| = \frac{b-a}{2^n} $

In [ ]:
import numpy as np

def right_f(x, k):
    return np.exp(-x) * np.sum([x ** n / math.factorial(n) for n in range(k+1)]) - 0.025

def left_f(x, k):
    return np.exp(-x) * np.sum([x ** n / math.factorial(n) for n in range(k)]) - 0.975

def dichotomy_method(f):
    x_next, x = 0, 1
    while np.sign(f(x_next, k)) == np.sign(f(x, k)):
        x_next += 1

    epsilon = 1e-6
    for i in range(1000):
        if np.abs(x_next - x) < epsilon:
            return x_next
        if np.sign(f((x_next + x) / 2, k)) == np.sign(f(x, k)):
            x, x_next = x_next, (x_next + x) / 2
        else:
            x_next = (x_next + x) / 2


k = 5
x_dichotomy_r = dichotomy_method(right_f)
print(x_dichotomy_r)
x_dichotomy_l = dichotomy_method(left_f)
print(x_dichotomy_l)





11.668331682682037
1.6234865188598633


##Задача 2
\begin{equation*}
A_{\varphi} =
\begin{pmatrix}
2 & -5 & 8 \\
-1 & 2 & -3 \\
2 & -5 & 7 \\
\end{pmatrix}
\end{equation*}
<br>
<br>

\begin{equation*}
\mathbf{e_{1}} =
\begin{pmatrix}
1 & 1 & -4\
\end{pmatrix}^{T}
\end{equation*}

\begin{equation*}
\mathbf{e_{2}} =
\begin{pmatrix}
1 & 2 & -6\
\end{pmatrix}^{T}
\end{equation*}

\begin{equation*}
\mathbf{e_{3}} =
\begin{pmatrix}
1 & -1 & -1\
\end{pmatrix}^{T}
\end{equation*}

<br>
<br>

\begin{equation*}
\mathbf{\overline{e_{1}}} =
\begin{pmatrix}
1 & 1 & 0\
\end{pmatrix}^{T}
\end{equation*}

\begin{equation*}
\mathbf{\overline{e_{2}}} =
\begin{pmatrix}
2 & 3 & 2\
\end{pmatrix}^{T}
\end{equation*}

\begin{equation*}
\mathbf{\overline{e_{3}}} =
\begin{pmatrix}
2 & 4 & -5\
\end{pmatrix}^{T}
\end{equation*}


In [ ]:
import numpy as np
A_P = np.array([[2, -5, 8],
                [-1, 2, -3],
                [2, -5, 7]])

P = np.array([[1, 1, 1],
              [1, 2, -1],
              [-4, -6, 1]])

Q = np.array([[1, 2, 2],
              [1, 3, 4],
              [0, 2, 5]])

A_P = np.array([[3, 0], [1, 3]])

P1 = np.array([[1, 1],
              [1, 2]])

Q1 = np.array([[1, 2],
              [0, 1],])


In [ ]:
P_inv = np.linalg.inv(P)

T1 = np.linalg.inv(P1) @ Q1
T = np.dot(P_inv, Q)

print("Матрица перехода T:", T1)
print(T)

Матрица перехода T: [[  2. -10. -19.]
 [  1.  -5.  -9.]
 [  0.   1.   2.]]
[[-11. -35. -51.]
 [  8.  25.  36.]
 [  4.  12.  17.]]


In [ ]:
T_inv = np.linalg.inv(T)
A_Q = np.dot(np.dot(T_inv, A_P), T)
print(A_Q)

[[ -555. -1805. -2647.]
 [  423.  1373.  2012.]
 [ -170.  -551.  -807.]]
